version: '2'

networks:
  limnet:

services:

  178.22.11.09_peer.proxdag.io:
    container_name: 178.22.11.09_peer.proxdag.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=178.22.11.09_peer.proxdag.io
    - CORE_PEER_IP_ADDRESS=178.22.11.09
    - GOSHIMMER_ENDPOINT=goshimmer.proxdag.io:8080
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    - ../proxdag:/autopeering
    - ../graph:/graph
    - ../dyncommittee:/dyncommittee
    networks:
    - proxdag

  33.26.189.20_peer.proxdag.io:
    container_name: 33.26.189.20_peer.proxdag.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=33.26.189.20_peer.proxdag.io
    - CORE_PEER_IP_ADDRESS=33.26.189.20
    - GOSHIMMER_ENDPOINT=goshimmer.proxdag.io:8080
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    - ../proxdag:/autopeering
    - ../graph:/graph
    - ../dyncommittee:/dyncommittee
    networks:
    - proxdag

  23.173.32.12_peer.proxdag.io:
    container_name: 23.173.32.12_peer.proxdag.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=23.173.32.12_peer.proxdag.io
    - CORE_PEER_IP_ADDRESS=23.173.32.12
    - GOSHIMMER_ENDPOINT=goshimmer.proxdag.io:8080
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    - ../proxdag:/autopeering
    - ../graph:/graph
    - ../dyncommittee:/dyncommittee
    networks:
    - proxdag

  99.21.221.11_peer.proxdag.io:
    container_name: 99.21.221.11_peer.proxdag.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=99.21.221.11_peer.proxdag.io
    - CORE_PEER_IP_ADDRESS=99.21.221.11
    - GOSHIMMER_ENDPOINT=goshimmer.proxdag.io:8080
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    - ../proxdag:/autopeering
    - ../graph:/graph
    - ../dyncommittee:/dyncommittee
    networks:
    - proxdag

  239.33.21.78_peer.proxdag.io:
    container_name: 239.33.21.78_peer.proxdag.io
    image: ubuntu:latest
    environment:
    - CORE_PEER_ID=239.33.21.78_peer.proxdag.io
    - CORE_PEER_IP_ADDRESS=239.33.21.78
    - GOSHIMMER_ENDPOINT=goshimmer.proxdag.io:8080
    command: /bin/bash /entry/hello.sh
    working_dir: /entry
    volumes:
    - ./entry:/entry
    - ../proxdag:/autopeering
    - ../graph:/graph
    - ../dyncommittee:/dyncommittee
    networks:
    - proxdag

